import Head from 'next/head'



  const cart = () => {
  return (
  
  <>
<Head>
  <title>Cart</title>
  <meta name="description" content="Generated by create next app" />
  <link rel="icon" href="/favicon.ico" />
</Head>
      <p>Cart.</p>
  </>

  
  
  )
}

export default cart